fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-tidy
        args: [--config-file=./.clang-tidy,-header-filter=.*]
        exclude: ^(.*\.h)$
      - id: cppcheck
        args: [--suppress=invalidPrintfArgType_sint,--suppress=unmatchedSuppression,--suppress=missingInclude,--suppress=invalidScanfArgType_int,--suppress=invalidPrintfArgType_uint,--suppress=shadowVariable,--suppress=shiftTooManyBitsSigned,--suppress=unusedFunction,--suppress=unknownMacro,--suppress=invalidPrintfArgType_s,--suppress=ConfigurationNotChecked,--suppress=resourceLeak,--suppress=unusedVariable,--suppress=va_end_missing,--suppress=wrongPrintfScanfArgNum,--suppress=bufferAccessOutOfBounds,--suppress=invalidFunctionArg,--suppress=invalidscanf,--suppress=invalidPrintfArgType_float,--suppress=nullPointer,--suppress=variableScope,--suppress=knownConditionTrueFalse,--suppress=toomanyconfigs,--suppress=unusedStructMember,--suppress=arithOperationsOnVoidPointer,--suppress=constParameter,--suppress=duplicateExpression,--suppress=memleak,--suppress=syntaxError,--suppress=unreadVariable,--suppress=doubleFree,--suppress=staticStringCompare,--suppress=stringCompare,--suppress=memleakOnRealloc,--suppress=noValidConfiguration,--suppress=assignmentInAssert,--suppress=nullPointerArithmetic]
        exclude: ^(tests/printf/picolibc-testcases.h|tests/printf/glibc-tst-printf-binary-main.h)$
      - id: cpplint
        args: ["--filter=-legal/copyright,-whitespace/braces,-whitespace/parens,-whitespace/newline,-whitespace/tab,-runtime/printf,-build/include_order,-whitespace/empty_loop_body,-readability/casting,-whitespace/line_length,-runtime/int,-whitespace/semicolon,-whitespace/comments,-whitespace/comma,-build/include_subdir,-readability/braces,-whitespace/indent,-readability/multiline_comment,-readability/nolint,-whitespace/operators,-readability/fn_size,-whitespace/blank_line,-build/header_guard,-readability/multiline_string,-runtime/arrays,-runtime/threadsafe_fn,-build/include,-build/c++11,-build/storage_class,-readability/alt_tokens,-readability/check"]
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
      - id: shellcheck
        args: ["-o", "all"]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.34.0
    hooks:
      - id: commitizen
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=3000']   # Obviously modify this if you really need to check-in a very large file
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: ^(test-data/outputs)
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: ['--fix=no']
      - id: trailing-whitespace
        exclude: ^test-data/outputs/
